# Population data

https://data.cso.ie/table/PEA01

In [1]:
import pandas as pd
import matplotlib

In [2]:
filename="PEA01.20260102T110146.csv"

df = pd.read_csv(filename)
df.head()

,STATISTIC Label,Year,Age Group,Sex,UNIT,VALUE
0,Population Estimates (Persons in April),1950,Under 1 year,Both sexes,Thousand,61.1
1,Population Estimates (Persons in April),1950,Under 1 year,Male,Thousand,31.4
2,Population Estimates (Persons in April),1950,Under 1 year,Female,Thousand,29.7
3,Population Estimates (Persons in April),1950,0 - 4 years,Both sexes,Thousand,NaN
4,Population Estimates (Persons in April),1950,0 - 4 years,Male,Thousand,NaN

In [3]:
df["Age Group"].unique()

<StringArray>
[     'Under 1 year',       '0 - 4 years',      '0 - 14 years',
       '1 - 4 years',       '5 - 9 years',     '10 - 14 years',
     '15 - 19 years',     '15 - 24 years', '15 years and over',
     '20 - 24 years',     '25 - 29 years',     '25 - 44 years',
     '30 - 34 years',     '35 - 39 years',     '40 - 44 years',
     '45 - 49 years',     '45 - 64 years',     '50 - 54 years',
     '55 - 59 years',     '60 - 64 years',     '65 - 69 years',
 '65 years and over',     '70 - 74 years',     '75 - 79 years',
     '80 - 84 years', '85 years and over',          'All ages']
Length: 27, dtype: str

In [4]:
both = df[df["Sex"] == "Both sexes"]
both = both[both["Age Group"] == "All ages"]
both.head()

,STATISTIC Label,Year,Age Group,Sex,UNIT,VALUE
78,Population Estimates (Persons in April),1950,All ages,Both sexes,Thousand,2969.0
159,Population Estimates (Persons in April),1951,All ages,Both sexes,Thousand,2960.6
240,Population Estimates (Persons in April),1952,All ages,Both sexes,Thousand,2952.9
321,Population Estimates (Persons in April),1953,All ages,Both sexes,Thousand,2949.0
402,Population Estimates (Persons in April),1954,All ages,Both sexes,Thousand,2941.2

In [5]:
both["Year"].unique()

array([1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960,
       1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004,
       2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025])

In [ ]:
both.plot(y="VALUE", x="Year")